kafka:
  bootstrap-servers: localhost:9092
server:
  port: 8084
spring:
  application:
    name: payment-service
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

